// Demo batch fixture data — inlined from fixtures/demo-batch.json
// Generated by solver/src/demo-cli.ts. Pool is 1:1 so virtual reserves equal liquidity.

const raw = {
  generatedBy: 'solver/src/demo-cli.ts',
  note: 'Batch with real reservation values, solved exactly. Pool is 1:1 so virtual reserves equal liquidity.',
  liquidity: '0x3635c9adc5dea00000',
  r0: '0x3635c9adc5dea00000',
  r1: '0x3635c9adc5dea00000',
  orderCount: 6,
  sellingCurrency0: ['0x1', '0x1', '0x1', '0x1', '0x0', '0x0'],
  ask: [
    '0xc3663566a580000',
    '0xce80612991d0000',
    '0xd87e55590018000',
    '0xe6ed27d66680000',
    '0xca0f82db99b0000',
    '0xff59ee833b30000',
  ],
  budget: [
    '0x1a055690d9db80000',
    '0x15af1d78b58c40000',
    '0x22b1c8c1227a00000',
    '0x1158e460913d00000',
    '0xa688906bd8b00000',
    '0xd02ab486cedc0000',
  ],
  dominantSellsCurrency0: '0x1',
  y: [
    '0x1a055690d9db80000',
    '0x10701f1f26aa3f889',
    '0x0',
    '0x0',
    '0xa688906bd8b00000',
    '0x0',
  ],
  x: [
    '0x18a7fd9ef8d897322',
    '0xf9268fc047090dd1',
    '0x0',
    '0x0',
    '0xa688906bd8b00000',
    '0x0',
  ],
  burn: '0x116ad5385faf29ca',
  M: '0xa688906bd8b00000',
  totalIn: '0x2a7575b00085bf889',
  totalPaid: '0x283a669afd49280f3',
}

const WAD = 10n ** 18n

function hex(s: string): bigint {
  return BigInt(s)
}

function toEther(wei: bigint): number {
  return Number((wei * 10000n) / WAD) / 10000
}

export interface DemoOrder {
  index: number
  sellsCurrency0: boolean
  ask: bigint
  askEther: number
  budget: bigint
  budgetEther: number
  filled: bigint
  filledEther: number
  paid: bigint
  paidEther: number
  refund: bigint
  refundEther: number
  outcome: 'full' | 'partial' | 'excluded' | 'ineligible'
  label: string
}

export interface DemoBatch {
  orderCount: number
  orders: DemoOrder[]
  burn: bigint
  burnEther: number
  totalIn: bigint
  totalInEther: number
  totalPaid: bigint
  burnPpm: number
  referencePrice: number // 1.0 at 1:1 pool
}

function classifyOrder(
  ask: bigint,
  budget: bigint,
  filled: bigint,
): DemoOrder['outcome'] {
  if (ask > WAD) return 'ineligible'
  if (filled === 0n) return 'excluded'
  if (filled >= budget) return 'full'
  return 'partial'
}

export function parseDemoBatch(): DemoBatch {
  const n = raw.orderCount
  const orders: DemoOrder[] = []

  for (let i = 0; i < n; i++) {
    const ask = hex(raw.ask[i])
    const budget = hex(raw.budget[i])
    const filled = hex(raw.y[i])
    const paid = hex(raw.x[i])
    const sellsCurrency0 = raw.sellingCurrency0[i] === '0x1'
    const refund = budget - filled
    const outcome = classifyOrder(ask, budget, filled)
    const label = outcome === 'full'
      ? 'Filled'
      : outcome === 'partial'
      ? 'Partial'
      : outcome === 'ineligible'
      ? 'Ineligible'
      : 'Excluded'

    orders.push({
      index: i,
      sellsCurrency0,
      ask,
      askEther: toEther(ask),
      budget,
      budgetEther: toEther(budget),
      filled,
      filledEther: toEther(filled),
      paid,
      paidEther: toEther(paid),
      refund,
      refundEther: toEther(refund),
      outcome,
      label,
    })
  }

  const burn = hex(raw.burn)
  const totalIn = hex(raw.totalIn)
  const totalPaid = hex(raw.totalPaid)
  const burnPpm = totalIn > 0n ? Number((burn * 1_000_000n) / totalIn) : 0

  return {
    orderCount: n,
    orders,
    burn,
    burnEther: toEther(burn),
    totalIn,
    totalInEther: toEther(totalIn),
    totalPaid,
    burnPpm,
    referencePrice: 1.0,
  }
}

export const DEMO_BATCH = parseDemoBatch()
