// Generated subset of local Foundry artifacts; verified by the offline wallet tests.

export const ORDER_BOOK_ABI = [
  {"type":"function","name":"DOMAIN_SEPARATOR","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"ORDER_TYPEHASH","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"SNAPSHOT_TYPEHASH","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"admissionPaused","inputs":[],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"batchState","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint8","internalType":"enum OtterOrderBook.State"}],"stateMutability":"view"},
  {"type":"function","name":"batches","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"closesAt","type":"uint64","internalType":"uint64"},{"name":"count","type":"uint32","internalType":"uint32"},{"name":"terminal","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"claim","inputs":[{"name":"currency","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"recipient","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"claimable","inputs":[{"name":"trader","type":"address","internalType":"address"},{"name":"currency","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"configVersionOf","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"currency0Of","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"currency1Of","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"currentBatchId","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"executionDeadline","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
  {"type":"function","name":"expire","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"expireUnsupportedFees","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"getOrders","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"orders","type":"tuple[]","internalType":"struct OtterOrderBook.Order[]","components":[{"name":"trader","type":"address","internalType":"address"},{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"sellingCurrency0","type":"bool","internalType":"bool"},{"name":"ask","type":"uint256","internalType":"uint256"},{"name":"budget","type":"uint256","internalType":"uint256"},{"name":"deadline","type":"uint256","internalType":"uint256"},{"name":"nonce","type":"uint256","internalType":"uint256"},{"name":"configVersion","type":"uint256","internalType":"uint256"},{"name":"epoch","type":"uint256","internalType":"uint256"},{"name":"maxExecutionTime","type":"uint256","internalType":"uint256"}]}],"stateMutability":"view"},
  {"type":"function","name":"invalidateNonces","inputs":[{"name":"word","type":"uint256","internalType":"uint256"},{"name":"mask","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"liquidityGuardOf","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"nonceBitmap","inputs":[{"name":"trader","type":"address","internalType":"address"},{"name":"word","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"bits","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"orderRecovered","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"},{"name":"index","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"previewEpoch","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"id","type":"uint256","internalType":"uint256"},{"name":"closesAt","type":"uint64","internalType":"uint64"},{"name":"executeUntil","type":"uint64","internalType":"uint64"},{"name":"configVersion","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"refundOrder","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"epoch","type":"uint256","internalType":"uint256"},{"name":"index","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"registered","inputs":[{"name":"poolId","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"rewardPolicyHashOf","inputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"settlement","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"submit","inputs":[{"name":"orders","type":"tuple[]","internalType":"struct OtterOrderBook.Order[]","components":[{"name":"trader","type":"address","internalType":"address"},{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"sellingCurrency0","type":"bool","internalType":"bool"},{"name":"ask","type":"uint256","internalType":"uint256"},{"name":"budget","type":"uint256","internalType":"uint256"},{"name":"deadline","type":"uint256","internalType":"uint256"},{"name":"nonce","type":"uint256","internalType":"uint256"},{"name":"configVersion","type":"uint256","internalType":"uint256"},{"name":"epoch","type":"uint256","internalType":"uint256"},{"name":"maxExecutionTime","type":"uint256","internalType":"uint256"}]},{"name":"signatures","type":"bytes[]","internalType":"bytes[]"}],"outputs":[{"name":"batchId","type":"uint256","internalType":"uint256"}],"stateMutability":"payable"},
  {"type":"function","name":"windowLength","inputs":[],"outputs":[{"name":"","type":"uint64","internalType":"uint64"}],"stateMutability":"view"},
  {"type":"event","name":"OrderSubmitted","inputs":[{"name":"poolId","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"batchId","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"trader","type":"address","indexed":true,"internalType":"address"},{"name":"index","type":"uint32","indexed":false,"internalType":"uint32"},{"name":"orderHash","type":"bytes32","indexed":false,"internalType":"bytes32"},{"name":"order","type":"tuple","indexed":false,"internalType":"struct OtterOrderBook.Order","components":[{"name":"trader","type":"address","internalType":"address"},{"name":"poolId","type":"bytes32","internalType":"bytes32"},{"name":"sellingCurrency0","type":"bool","internalType":"bool"},{"name":"ask","type":"uint256","internalType":"uint256"},{"name":"budget","type":"uint256","internalType":"uint256"},{"name":"deadline","type":"uint256","internalType":"uint256"},{"name":"nonce","type":"uint256","internalType":"uint256"},{"name":"configVersion","type":"uint256","internalType":"uint256"},{"name":"epoch","type":"uint256","internalType":"uint256"},{"name":"maxExecutionTime","type":"uint256","internalType":"uint256"}]}],"anonymous":false},
  {"type":"error","name":"AdmissionPaused","inputs":[]},
  {"type":"error","name":"AlreadyCredited","inputs":[]},
  {"type":"error","name":"AlreadyRecovered","inputs":[]},
  {"type":"error","name":"AlreadyReleased","inputs":[]},
  {"type":"error","name":"AlreadySettled","inputs":[]},
  {"type":"error","name":"AmountOutOfDomain","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"BadSignature","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"BatchFull","inputs":[]},
  {"type":"error","name":"BudgetExceeded","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"CountMismatch","inputs":[{"name":"supplied","type":"uint256","internalType":"uint256"},{"name":"expected","type":"uint32","internalType":"uint32"}]},
  {"type":"error","name":"DigestMismatch","inputs":[]},
  {"type":"error","name":"ExecutionExpired","inputs":[{"name":"executeUntil","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"FeesStillSupported","inputs":[]},
  {"type":"error","name":"InexactTransfer","inputs":[{"name":"currency","type":"address","internalType":"address"},{"name":"expected","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"Insolvent","inputs":[{"name":"currency","type":"address","internalType":"address"}]},
  {"type":"error","name":"InsufficientExecutionValidity","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"InvalidClaim","inputs":[]},
  {"type":"error","name":"InvalidClock","inputs":[]},
  {"type":"error","name":"InvalidCurrencies","inputs":[]},
  {"type":"error","name":"InvalidLiquidityGuard","inputs":[]},
  {"type":"error","name":"InvalidOrderIndex","inputs":[]},
  {"type":"error","name":"InvalidRewardPolicy","inputs":[]},
  {"type":"error","name":"InvalidSnapshot","inputs":[]},
  {"type":"error","name":"InvalidTrader","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"LengthMismatch","inputs":[]},
  {"type":"error","name":"NativeTransferFailed","inputs":[]},
  {"type":"error","name":"NativeValueMismatch","inputs":[{"name":"supplied","type":"uint256","internalType":"uint256"},{"name":"required","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"NoRewardWeight","inputs":[]},
  {"type":"error","name":"NonceUsed","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"NotExecuting","inputs":[]},
  {"type":"error","name":"NotOwner","inputs":[]},
  {"type":"error","name":"NotRefundable","inputs":[]},
  {"type":"error","name":"NotSettlement","inputs":[]},
  {"type":"error","name":"OrderExpired","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"PoolAlreadyRegistered","inputs":[]},
  {"type":"error","name":"PoolNotRegistered","inputs":[]},
  {"type":"error","name":"PreviousBatchUnsettled","inputs":[{"name":"batchId","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"ReentrantCall","inputs":[]},
  {"type":"error","name":"RefundTooEarly","inputs":[{"name":"refundableAt","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"SettlementAlreadySet","inputs":[]},
  {"type":"error","name":"SnapshotMissing","inputs":[]},
  {"type":"error","name":"UnsupportedRewardPrice","inputs":[]},
  {"type":"error","name":"WindowClosed","inputs":[]},
  {"type":"error","name":"WindowStillOpen","inputs":[]},
  {"type":"error","name":"WrongConfiguration","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"WrongEpoch","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"WrongPool","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"ZeroBudget","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"ZeroCurrency","inputs":[]}
] as const

export const SETTLEMENT_ABI = [
  {"type":"function","name":"orderBook","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract OtterOrderBook"}],"stateMutability":"view"},
  {"type":"function","name":"rewardLedger","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract OtterRewardLedger"}],"stateMutability":"view"},
  {"type":"error","name":"BudgetExceeded","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"DominanceViolated","inputs":[{"name":"totalIn","type":"uint256","internalType":"uint256"},{"name":"M","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"EmptyBatch","inputs":[]},
  {"type":"error","name":"HookAlreadySet","inputs":[]},
  {"type":"error","name":"IndividualRationality","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"IneligibleMustBeUnfilled","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"InexactTransfer","inputs":[{"name":"currency","type":"address","internalType":"Currency"},{"name":"expected","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"Insolvent","inputs":[{"name":"currency","type":"address","internalType":"Currency"}]},
  {"type":"error","name":"InvalidCallback","inputs":[]},
  {"type":"error","name":"InvalidExecutionWindow","inputs":[]},
  {"type":"error","name":"InvalidHook","inputs":[{"name":"supplied","type":"address","internalType":"address"}]},
  {"type":"error","name":"InvalidSwapDelta","inputs":[]},
  {"type":"error","name":"LengthMismatch","inputs":[]},
  {"type":"error","name":"MinorityFillWrong","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"NativeSenderUnauthorized","inputs":[]},
  {"type":"error","name":"NegativeBurn","inputs":[{"name":"paid","type":"uint256","internalType":"uint256"},{"name":"available","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"NoLiquidity","inputs":[]},
  {"type":"error","name":"NonZeroFee","inputs":[{"name":"fee","type":"uint24","internalType":"uint24"}]},
  {"type":"error","name":"NotExclusiveSolver","inputs":[{"name":"exclusiveUntil","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"NotOwner","inputs":[]},
  {"type":"error","name":"NotPoolManager","inputs":[]},
  {"type":"error","name":"PaymentExceedsMarginal","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"PaymentExceedsSpot","inputs":[{"name":"i","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"PoolOutputShortfall","inputs":[{"name":"have","type":"uint256","internalType":"uint256"},{"name":"owed","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"ReentrantCall","inputs":[]},
  {"type":"error","name":"SnapshotMismatch","inputs":[]},
  {"type":"error","name":"UnexpectedInputConsumption","inputs":[{"name":"requested","type":"uint256","internalType":"uint256"},{"name":"consumed","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"UnsupportedPrice","inputs":[{"name":"sqrtPriceX96","type":"uint160","internalType":"uint160"}]},
  {"type":"error","name":"UnsupportedProtocolFee","inputs":[{"name":"fee","type":"uint24","internalType":"uint24"}]}
] as const

export const REWARD_LEDGER_ABI = [
  {"type":"function","name":"claim","inputs":[{"name":"currency","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"},{"name":"recipient","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"claimable","inputs":[{"name":"","type":"address","internalType":"address"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"orderBook","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract OtterOrderBook"}],"stateMutability":"view"},
  {"type":"function","name":"policyHashOf","inputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"settlement","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"error","name":"AlreadyCredited","inputs":[]},
  {"type":"error","name":"InexactTransfer","inputs":[{"name":"currency","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}]},
  {"type":"error","name":"Insolvent","inputs":[{"name":"currency","type":"address","internalType":"address"}]},
  {"type":"error","name":"InvalidClaim","inputs":[]},
  {"type":"error","name":"InvalidEpoch","inputs":[]},
  {"type":"error","name":"InvalidPolicy","inputs":[]},
  {"type":"error","name":"InvalidWeights","inputs":[]},
  {"type":"error","name":"NativeTransferFailed","inputs":[]},
  {"type":"error","name":"NotSettlement","inputs":[]},
  {"type":"error","name":"ReentrantCall","inputs":[]}
] as const

export const ERC20_ABI = [
  {"type":"function","name":"decimals","inputs":[],"outputs":[{"type":"uint8","name":""}],"stateMutability":"view"},
  {"type":"function","name":"allowance","inputs":[{"type":"address","name":"owner"},{"type":"address","name":"spender"}],"outputs":[{"type":"uint256","name":""}],"stateMutability":"view"},
  {"type":"function","name":"approve","inputs":[{"type":"address","name":"spender"},{"type":"uint256","name":"amount"}],"outputs":[{"type":"bool","name":""}],"stateMutability":"nonpayable"}
] as const
